### ISSUE TITLE
"Error: couldn't download the model file"

### ISSUE THREAD

**Issue by javierivanfigueroa** [mkiol/dsnote#31] opened 2023-09-24 20:23 UTC
Hello. First of all, thank you for your work. It looks fantastic. At least, until now, I couldn't try it, since the following problem appears (I took a screenshot so you can see it: "01. Text to speech Spanish - Error") By the way, I had no problem downloading in English.

![02  English OK](https://github.com/mkiol/dsnote/assets/14182275/4f1d6df0-55d2-4bbd-871e-70f84194e27d)
![01  Text to speech Spanish - Error](https://github.com/mkiol/dsnote/assets/14182275/f0017a5b-38e2-455d-882a-554e6e3b24c7)

Sorry if this request is not well made, it's my first time using Github.

Thanks for your job.

**Comment by mkiol** [comment] 2023-09-25 07:55
Thank you for the report.

I can confirm the problem. It affects all "Piper" model. 

Yesterday, the author of Piper has updated all models (a tiny change in names). Speech Note after download verifies the checksum. Because models were updated, the checksum is invalid.

This dbd311af9505191e666f129080437f4b9adeb78b resolves the issue. The fix will be included in next version. 

I'm planing to push new release today.

**Comment by mkiol** [comment] 2023-09-25 13:19
Fixed in version 4.2.0.

dbd311af9505191e666f129080437f4b9adeb78b

**Closed as completed by mkiol** 2023-09-25 13:19 UTC

**Comment by javierivanfigueroa** [comment] 2023-09-25 15:58
It works now! Thankyou!
