### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by atlochowski** [mkiol/dsnote#1] opened 2021-04-22 19:47 UTC
After download Polish or English lang (haven't tried other languages) app crashes.

```
wi 22 21:44:41 Sailfish kernel: [19:44:41.420937] [00000003A3D066CB] [VosMC]  wlan: [E :HDP] hdd_tx_rx_pkt_cnt_stat_timer_handler: Disable split scan
kwi 22 21:44:44 Sailfish [7938]: [D] unknown:0 - md5 checksum: "08a02b383a9bc93c8a8ad188dbf79bc9" "/home/nemo/Downloads/DeepSpeech models/en.scorer"
kwi 22 21:44:44 Sailfish [7938]: [D] unknown:0 - successfully downloaded: scorer "en"
kwi 22 21:44:44 Sailfish lipstick[5289]: TensorFlow: v2.3.0-6-g23ad988
kwi 22 21:44:44 Sailfish [7938]: [D] unknown:0 - processing thread started
kwi 22 21:44:44 Sailfish lipstick[5289]: DeepSpeech: v0.9.3-0-gf2e9c85
kwi 22 21:44:44 Sailfish mapplauncherd[6123]: Boosted process (pid=7938) was terminated due to signal 4
kwi 22 21:44:54 Sailfish kernel: [19:44:54.367088] [00000003B2A13831] [wpa_s]  wlan: [E :HDD] wlan_hdd_get_frame_logs: Frame Logging not init!
kwi 22 21:45:01 Sailfish kernel: binder: 5309 RLIMIT_NICE not set
kwi 22 21:45:01 Sailfish kernel: binder: 5308 RLIMIT_NICE not set
kwi 22 21:45:01 Sailfish kernel: binder: 7253 RLIMIT_NICE not set
kwi 22 21:45:01 Sailfish kernel: binder: 7253 RLIMIT_NICE not set
kwi 22 21:45:01 Sailfish kernel: binder: 5309 RLIMIT_NICE not set
kwi 22 21:45:01 Sailfish kernel: binder: 5308 RLIMIT_NICE not set
kwi 22 21:45:01 Sailfish [8180]: [W] unknown:0 - ds is not inited, cannot start mic
kwi 22 21:45:01 Sailfish kernel: [19:45:01.606666] [00000003BAEA3072] [wpa_s]  wlan: [E :HDD] wlan_hdd_get_frame_logs: Frame Logging not init!
kwi 22 21:45:01 Sailfish [8180]: [W] unknown:286 - file:///usr/lib/qt5/qml/Sailfish/Silica/private/TextBase.qml:286: TypeError: Cannot call method 'createObject' of null
kwi 22 21:45:01 Sailfish lipstick[5289]: [W] unknown:0 - WindowPixmapItem does not have a source texture, cover will be dropped..
kwi 22 21:45:02 Sailfish [8180]: [D] unknown:0 - md5 checksum: "afcc08e56f024655c30187a41c4e8c9c" "/home/nemo/Downloads/DeepSpeech models/en.tflite"
kwi 22 21:45:02 Sailfish booster-silica-qt5[8246]: [D] unknown:0 - Using Wayland-EGL
kwi 22 21:45:02 Sailfish mapplauncherd[8246]: SilicaBooster: Initiate asynchronous preload.
kwi 22 21:45:04 Sailfish tracker-store[8223]: OK
kwi 22 21:45:07 Sailfish kernel: [19:45:07.443620] [00000003C1983BFC] [wpa_s]  wlan: [E :HDD] wlan_hdd_get_frame_logs: Frame Logging not init!
kwi 22 21:45:11 Sailfish [8180]: [D] unknown:0 - md5 checksum: "08a02b383a9bc93c8a8ad188dbf79bc9" "/home/nemo/Downloads/DeepSpeech models/en.scorer"
kwi 22 21:45:11 Sailfish lipstick[5289]: TensorFlow: v2.3.0-6-g23ad988
kwi 22 21:45:11 Sailfish lipstick[5289]: DeepSpeech: v0.9.3-0-gf2e9c85
kwi 22 21:45:11 Sailfish [8180]: [D] unknown:0 - processing thread started
kwi 22 21:45:12 Sailfish mapplauncherd[6123]: Boosted process (pid=8180) was terminated due to signal 4
kwi 22 21:45:16 Sailfish kernel: binder: 7253 RLIMIT_NICE not set
kwi 22 21:45:16 Sailfish kernel: binder: 5309 RLIMIT_NICE not set
kwi 22 21:45:16 Sailfish kernel: binder: 5308 RLIMIT_NICE not set
kwi 22 21:45:16 Sailfish kernel: binder: 5309 RLIMIT_NICE not set
kwi 22 21:45:16 Sailfish kernel: binder: 5308 RLIMIT_NICE not set
kwi 22 21:45:16 Sailfish kernel: binder: 7253 RLIMIT_NICE not set
kwi 22 21:45:17 Sailfish [8246]: [W] unknown:0 - ds is not inited, cannot start mic
kwi 22 21:45:17 Sailfish kernel: [19:45:17.435136] [00000003CD076FB9] [wpa_s]  wlan: [E :HDD] wlan_hdd_get_frame_logs: Frame Logging not init!
kwi 22 21:45:17 Sailfish [8246]: [W] unknown:286 - file:///usr/lib/qt5/qml/Sailfish/Silica/private/TextBase.qml:286: TypeError: Cannot call method 'createObject' of null
kwi 22 21:45:17 Sailfish lipstick[5289]: [W] unknown:0 - WindowPixmapItem does not have a source texture, cover will be dropped..
kwi 22 21:45:17 Sailfish [8246]: [D] unknown:0 - md5 checksum: "afcc08e56f024655c30187a41c4e8c9c" "/home/nemo/Downloads/DeepSpeech models/en.tflite"
kwi 22 21:45:18 Sailfish booster-silica-qt5[8276]: [D] unknown:0 - Using Wayland-EGL
kwi 22 21:45:18 Sailfish mapplauncherd[8276]: SilicaBooster: Initiate asynchronous preload.
kwi 22 21:45:23 Sailfish kernel: [19:45:23.282489] [00000003D3B8872E] [wpa_s]  wlan: [E :HDD] wlan_hdd_get_frame_logs: Frame Logging not init!
kwi 22 21:45:27 Sailfish [8246]: [D] unknown:0 - md5 checksum: "08a02b383a9bc93c8a8ad188dbf79bc9" "/home/nemo/Downloads/DeepSpeech models/en.scorer"
kwi 22 21:45:27 Sailfish lipstick[5289]: TensorFlow: v2.3.0-6-g23ad988
kwi 22 21:45:27 Sailfish lipstick[5289]: DeepSpeech: v0.9.3-0-gf2e9c85
kwi 22 21:45:27 Sailfish mapplauncherd[6123]: Boosted process (pid=8246) was terminated due to signal 4
kwi 22 21:45:30 Sailfish kernel: binder: 5309 RLIMIT_NICE not set
kwi 22 21:45:30 Sailfish kernel: binder: 5308 RLIMIT_NICE not set
kwi 22 21:45:30 Sailfish kernel: binder: 7253 RLIMIT_NICE not set
kwi 22 21:45:30 Sailfish kernel: binder: 7253 RLIMIT_NICE not set
kwi 22 21:45:30 Sailfish kernel: binder: 5308 RLIMIT_NICE not set
kwi 22 21:45:30 Sailfish kernel: binder: 5309 RLIMIT_NICE not set
kwi 22 21:45:31 Sailfish [8276]: [W] unknown:0 - ds is not inited, cannot start mic
kwi 22 21:45:31 Sailfish kernel: [19:45:31.422864] [00000003DD096759] [wpa_s]  wlan: [E :HDD] wlan_hdd_get_frame_logs: Frame Logging not init!
kwi 22 21:45:31 Sailfish [8276]: [W] unknown:286 - file:///usr/lib/qt5/qml/Sailfish/Silica/private/TextBase.qml:286: TypeError: Cannot call method 'createObject' of null
kwi 22 21:45:31 Sailfish lipstick[5289]: [W] unknown:0 - WindowPixmapItem does not have a source texture, cover will be dropped..
kwi 22 21:45:31 Sailfish [8276]: [D] unknown:0 - md5 checksum: "afcc08e56f024655c30187a41c4e8c9c" "/home/nemo/Downloads/DeepSpeech models/en.tflite"
kwi 22 21:45:32 Sailfish booster-silica-qt5[8302]: [D] unknown:0 - Using Wayland-EGL
kwi 22 21:45:32 Sailfish mapplauncherd[8302]: SilicaBooster: Initiate asynchronous preload.
kwi 22 21:45:37 Sailfish kernel: [19:45:37.203870] [00000003E3A70EC7] [wpa_s]  wlan: [E :HDD] wlan_hdd_get_frame_logs: Frame Logging not init!
kwi 22 21:45:41 Sailfish [8276]: [D] unknown:0 - md5 checksum: "08a02b383a9bc93c8a8ad188dbf79bc9" "/home/nemo/Downloads/DeepSpeech models/en.scorer"
kwi 22 21:45:41 Sailfish lipstick[5289]: TensorFlow: v2.3.0-6-g23ad988
kwi 22 21:45:41 Sailfish lipstick[5289]: DeepSpeech: v0.9.3-0-gf2e9c85
kwi 22 21:45:41 Sailfish [8276]: [D] unknown:0 - processing thread started
kwi 22 21:45:41 Sailfish mapplauncherd[6123]: Boosted process (pid=8276) was terminated due to signal 4
kwi 22 21:45:48 Sailfish kernel: [19:45:48.006659] [00000003F003EFF4] [wpa_s]  wlan: [E :HDD] wlan_hdd_get_frame_logs: Frame Logging not init!
```
device: Jolla C

**Comment by mkiol** [comment] 2021-04-23 09:32
Thanks for reporting. Indeed it crashes on JollaC :/

**Comment by mkiol** [comment] 2021-04-23 16:15
gdb output:

```
Thread 1 "harbour-dsnote" received signal SIGILL, Illegal instruction.
0xb6e58916 in ?? () from /usr/share/harbour-dsnote/lib/libdeepspeech.so
```

**Comment by mkiol** [comment] 2021-04-27 18:57
Root cause of SIGILL crash: `libdeepspeech.so` provided with the app was compiled for `armv7-a`, but Jolla C has `armv7` cpu.

**Comment by mkiol** [comment] 2021-04-28 20:04
Resolved by generic ARM build of `libdeepspeech.so` (4ea06d2f29c8b0cb622a5803d06b7fe2c0d4baf1)
Tested on Jolla1, JollaC, Xperia10 and PinePhone.

**Closed by mkiol** 2021-04-28 20:04 UTC
