### ISSUE TITLE
Error: “translation engine initialization has failed”.

### ISSUE THREAD

**Issue by Ixel242** [mkiol/dsnote#131] opened 2024-05-09 12:51 UTC
HI,
I installed a version of Speech Note, more or less 6 months ago, in my desktop computer: GEEKOM Mini IT11 Mini PC, i7-11390H (5,0 GHz), 32GB de RAM+1TB de SSD, on Majaro with xcfe4, **and all works(Speech to Text, Text to Speech and Machine Translation) without any problem**… but I tried again in 2 old laptops and all works **wIth the exception of translation**.

These old laptops are:
Lenovo Thinkpad T410 14,1" i5 540M, 8GB, SSD 250GB
Lenovo B580-M94A5GE - [Intel Core i5-3210M] 2.5 GHz, 8GB - DDR3, SSD 250GB

When I try to translate a text from English to Spanish or on the contrary, appears this comMent:
ERROR: TRANSLATION ENGINE INITIALIZATION HAS FAILED.

1. Trying to get the origin of this problem,  I checked that the plugin for the translation is contained in the correct folder;

2. Another possible origin could be the laptops age ( because they are old, more or less from 2014).

3. Also, I think that the installation that works correctly (on the desktop computer) was before the updating of Majaro and, on the laptops, Manjaro had been updated yet.

I'm new in linux  and I'm didn't find another way for getting something strange.

Could you help me to find the problem and its solution?

Thank you, in advance.

**Comment by mkiol** [comment] 2024-05-10 18:23
Hi. Thanks for the report.

Most likely CPU in your old laptop does not support AVX extension. Engine behind translator (Bergamot) needs AVX to work. This is similar problem to this one: https://github.com/mkiol/dsnote/issues/88

To make sure, please start Speech Note with `--verbose` option to see more logs.

```
flatpak run net.mkiol.SpeechNote --verbose
```

To check if AVX is supported in your CPU  you can use:

```
lscpu | grep avx
```

**Comment by mkiol** [comment] 2024-05-19 09:21
The problem is the lack of AVX in the CPU. I am closing for now. Feel free to re-open if you want to add more information.

**Closed as completed by mkiol** 2024-05-19 09:21 UTC
Labels: cpu

**Comment by Ixel242** [comment] 2024-05-19 16:38
Hi,

yes...you are correct, I've tried the commands in the Terminal and in different lines I have sentences  like:
"avx not supported but ds engine needs it"
"mnt not available because cpu doesn't have avx"

Thank you for your help!

**Comment by Ixel242** [comment] 2025-04-10 18:46
Hello,
I have a GEEKOM Mini IT11 Mini PC 11th with Intel® Core™ i7-11390H 11th Gen.Intel® Iris® Xe Graphics and 16Gb RAM.

I have discovered Spech Note's speech to text option, but I see that it runs slow with Vosk Large and with FasterWhisper Large-v3.

I don't have acceleration installed because I don't have an AMD or Nvidia graphics card, how you can see in the capture.

I would like to move my college notes from speech to text. Can I do anything to improve that speed? 

Thank you very much!






    En viernes, 10 de mayo de 2024, 20:23:43 CEST, mkiol ***@***.***> escribió:  
 
 


Hi. Thanks for the report.

Most likely CPU in your old laptop does not support AVX extension. Engine behind translator (Bergamot) needs AVX to work. This is similar problem to this one: #88

To make sure, please start Speech Note with --verbose option to see more logs.
flatpak run net.mkiol.SpeechNote --verbose

To check if AVX is supported in your CPU you can use:
lscpu | grep avx

**Comment by mkiol** [comment] 2025-04-13 15:38
> Can I do anything to improve that speed?

If your integrated GPU supports Vulkan, you can try enabling it for WhisperCpp. Usually Vulkan with an integrated GPU doesn't work well, but it's worth a try.

If Vulkan is supported, you should be able to enable Vulkan in the WhisperCpp engine settings:

![Image](https://github.com/user-attachments/assets/6be8ce8a-2120-4316-b9da-f70ea13b6c1f)

In general, without GPU the best performance will be with Vosk Small or WhisperCpp "Tiny" or "Base" model.
